### ISSUE TITLE
Post-Publishing Tasks Checklist

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-liberty-deep-dive#103]
Post-Publishing Tests (Tester)

- [x] Check appearance (contents, headings, paragraphs, code snippets, outputs, links) of the guide on openliberty.io
- [x] Clone repo and test finish directory with no error
- [x] test the start directory end-to-end

Other post-publishing tasks (to be done by the Admin Team)
- [x] Add description for the repo with link to guide's published website
- [x] Double check the SEO title and description are added for the guide
- [x] Create the Home and Branches wiki pages
- [x] Ensure automated test for PR and Continuous Tests are enabled for both `prod` and `staging` branches and are run by Github action, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
  - make sure test.yml has no draft and linter default branch is prod
  - [x] make sure that test.yml is updated
- [x] Ensure the automated tests are running successfully for the daily builds
  - [x] remove `draft-guide-x` from guides-common/.github/workflows/drafts-to-test.json 
- ~~Ensure the automated tests are running successfully for the daily docker image, if the guide uses a docker image~~
- ~~Enable pull creation notification on the repo for `was-lib-guides-alerts`, see [instruction](https://github.ibm.com/websphere/openliberty-guides-team/wiki/Subscribe-static-guide-repository-to-a-slack-channel)~~
- [x] Enable `prod` and `staging` branches lock down, see [instruction](https://github.ibm.com/was-liberty/openliberty-guides-team/wiki/Automation-Tests-For-OpenLiberty-Guides#setup-travis-ci-tests-for-openliberty-guides) 
  -  make sure the Branch protection rules were created
- [x] Add the new guide's repo to the `OpenLiberty/guides-getting-started` ZenHub board
- [x] Clean up branches, issues, and PRs
- ~~create blog issue~~
  - ~~issue link~~
- ~~Send announcement to slack channels~~
  - dev_advocates_java
  - was-lib-guides-dev
  - was-gm-testing
- [x] enable analytic
  - `Open Liberty - Guides - Individual Guide Clones` and `Individual Guides Referrals` dashboards  
- [x] Arrange a demo at the EOI meeting

**Comment by gkwan-ibm** [comment]
close
- all tasks were completed
